name: app Continuous Integration
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
env:
  DO_NOT_TRACK: 1
  NODE_OPTIONS: "--max-old-space-size=4096"
  TURBO_TELEMETRY_DISABLED: 1
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 22
      - name: Install dependencies
        run: npm install --ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
